# Generated by Django 5.2 on 2025-04-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepie',
            old_name='recepie_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='recepie',
            old_name='recepie_image',
            new_name='receipe_image',
        ),
    ]
